name: tapcalculator
description: "tap counter in flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  info_popup: ^4.3.1
  animated_flip_counter: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  dart_code_linter: ^1.1.2

flutter_icons:
  image_path: "assets/icon/icon.jpeg"
  android: true # can specify
  ios: true

flutter:
  uses-material-design: true
